-- CAT BREEDS --
INSERT INTO petbreeds VALUES('Abyssinian','Cat');
INSERT INTO petbreeds VALUES('Aegean','Cat');
INSERT INTO petbreeds VALUES('American Curl','Cat');
INSERT INTO petbreeds VALUES('American Bobtail','Cat');
INSERT INTO petbreeds VALUES('American Shorthair','Cat');
INSERT INTO petbreeds VALUES('American Wirehair','Cat');
INSERT INTO petbreeds VALUES('Arabian Mau','Cat');
INSERT INTO petbreeds VALUES('Australian Mist','Cat');
INSERT INTO petbreeds VALUES('Asian','Cat');
INSERT INTO petbreeds VALUES('Asian Semi-longhair','Cat');
INSERT INTO petbreeds VALUES('Balinese','Cat');
INSERT INTO petbreeds VALUES('Bambino','Cat');
INSERT INTO petbreeds VALUES('Bengal','Cat');
INSERT INTO petbreeds VALUES('Birman','Cat');
INSERT INTO petbreeds VALUES('Bombay','Cat');
INSERT INTO petbreeds VALUES('Brazilian Shorthair','Cat');
INSERT INTO petbreeds VALUES('British Semi-longhair','Cat');
INSERT INTO petbreeds VALUES('British Shorthair','Cat');
INSERT INTO petbreeds VALUES('British Longhair','Cat');
INSERT INTO petbreeds VALUES('Burmese','Cat');
INSERT INTO petbreeds VALUES('Burmilla','Cat');
INSERT INTO petbreeds VALUES('California Spangled','Cat');
INSERT INTO petbreeds VALUES('Chantilly-Tiffany','Cat');
INSERT INTO petbreeds VALUES('Chartreux','Cat');
INSERT INTO petbreeds VALUES('Chausie','Cat');
INSERT INTO petbreeds VALUES('Cheetoh','Cat');
INSERT INTO petbreeds VALUES('Colorpoint Shorthair','Cat');
INSERT INTO petbreeds VALUES('Cornish Rex','Cat');
INSERT INTO petbreeds VALUES('Cymric','Cat');
INSERT INTO petbreeds VALUES('Cyprus','Cat');
INSERT INTO petbreeds VALUES('Devon Rex','Cat');
INSERT INTO petbreeds VALUES('Donskoy','Cat');
INSERT INTO petbreeds VALUES('Dragon Li','Cat');
INSERT INTO petbreeds VALUES('Dwarf cat','Cat');
INSERT INTO petbreeds VALUES('Egyptian Mau','Cat');
INSERT INTO petbreeds VALUES('European Shorthair','Cat');
INSERT INTO petbreeds VALUES('Exotic Shorthair','Cat');
INSERT INTO petbreeds VALUES('Foldex','Cat');
INSERT INTO petbreeds VALUES('German Rex','Cat');
INSERT INTO petbreeds VALUES('Havana Brown','Cat');
INSERT INTO petbreeds VALUES('Highlander','Cat');
INSERT INTO petbreeds VALUES('Himalayan','Cat');
INSERT INTO petbreeds VALUES('Japanese Bobtail','Cat');
INSERT INTO petbreeds VALUES('Javanese','Cat');
INSERT INTO petbreeds VALUES('Karelian Bobtail','Cat');
INSERT INTO petbreeds VALUES('Khao Manee','Cat');
INSERT INTO petbreeds VALUES('Korat','Cat');
INSERT INTO petbreeds VALUES('Korean Bobtail','Cat');
INSERT INTO petbreeds VALUES('Korn Ja','Cat');
INSERT INTO petbreeds VALUES('Kurilian Bobtail','Cat');
INSERT INTO petbreeds VALUES('LaPerm','Cat');
INSERT INTO petbreeds VALUES('Lykoi','Cat');
INSERT INTO petbreeds VALUES('Maine Coon','Cat');
INSERT INTO petbreeds VALUES('Manx','Cat');
INSERT INTO petbreeds VALUES('Mekong Bobtail','Cat');
INSERT INTO petbreeds VALUES('Minskin','Cat');
INSERT INTO petbreeds VALUES('Munchkin','Cat');
INSERT INTO petbreeds VALUES('Nebelung','Cat');
INSERT INTO petbreeds VALUES('Napoleon','Cat');
INSERT INTO petbreeds VALUES('Norwegian Forest cat','Cat');
INSERT INTO petbreeds VALUES('Ocicat','Cat');
INSERT INTO petbreeds VALUES('Ojos Azules','Cat');
INSERT INTO petbreeds VALUES('Oregon Rex','Cat');
INSERT INTO petbreeds VALUES('Oriental Bicolor','Cat');
INSERT INTO petbreeds VALUES('Oriental Shorthair','Cat');
INSERT INTO petbreeds VALUES('Oriental Longhair','Cat');
INSERT INTO petbreeds VALUES('PerFold','Cat');
INSERT INTO petbreeds VALUES('Persian (Modern Persian)','Cat');
INSERT INTO petbreeds VALUES('Persian (Traditional Persian)','Cat');
INSERT INTO petbreeds VALUES('Peterbald','Cat');
INSERT INTO petbreeds VALUES('Pixie-bob','Cat');
INSERT INTO petbreeds VALUES('Raas','Cat');
INSERT INTO petbreeds VALUES('Ragamuffin','Cat');
INSERT INTO petbreeds VALUES('Ragdoll','Cat');
INSERT INTO petbreeds VALUES('Russian Blue','Cat');
INSERT INTO petbreeds VALUES('Russian White, Black and Tabby','Cat');
INSERT INTO petbreeds VALUES('Sam Sawet','Cat');
INSERT INTO petbreeds VALUES('Savannah','Cat');
INSERT INTO petbreeds VALUES('Scottish Fold','Cat');
INSERT INTO petbreeds VALUES('Selkirk Rex','Cat');
INSERT INTO petbreeds VALUES('Serengeti','Cat');
INSERT INTO petbreeds VALUES('Serrade petit','Cat');
INSERT INTO petbreeds VALUES('Siamese','Cat');
INSERT INTO petbreeds VALUES('Siberian','Cat');
INSERT INTO petbreeds VALUES('Singapura','Cat');
INSERT INTO petbreeds VALUES('Snowshoe','Cat');
INSERT INTO petbreeds VALUES('Sokoke','Cat');
INSERT INTO petbreeds VALUES('Somali','Cat');
INSERT INTO petbreeds VALUES('Sphynx','Cat');
INSERT INTO petbreeds VALUES('Suphalak','Cat');
INSERT INTO petbreeds VALUES('Thai','Cat');
INSERT INTO petbreeds VALUES('Thai Lilac','Cat');
INSERT INTO petbreeds VALUES('Tonkinese','Cat');
INSERT INTO petbreeds VALUES('Toyger','Cat');
INSERT INTO petbreeds VALUES('Turkish Angora','Cat');
INSERT INTO petbreeds VALUES('Turkish Van','Cat');
INSERT INTO petbreeds VALUES('Ukrainian Levkoy','Cat');

--DOG BREEDS--
INSERT INTO petbreeds VALUES('Afghan Hound', 'Dog');
INSERT INTO petbreeds VALUES('Afghan Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Aidi', 'Dog');
INSERT INTO petbreeds VALUES('Airedale Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Akbash', 'Dog');
INSERT INTO petbreeds VALUES('Akita', 'Dog');
INSERT INTO petbreeds VALUES('Alaskan husky', 'Dog');
INSERT INTO petbreeds VALUES('Alaskan Klee Kai', 'Dog');
INSERT INTO petbreeds VALUES('Alaskan Malamute', 'Dog');
INSERT INTO petbreeds VALUES('Alaunt', 'Dog');
INSERT INTO petbreeds VALUES('Alopekis', 'Dog');
INSERT INTO petbreeds VALUES('Alpine Dachsbracke', 'Dog');
INSERT INTO petbreeds VALUES('Alpine Mastiff', 'Dog');
INSERT INTO petbreeds VALUES('Alpine Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('American Akita', 'Dog');
INSERT INTO petbreeds VALUES('American Bulldog', 'Dog');
INSERT INTO petbreeds VALUES('American Cocker Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('American English Coonhound', 'Dog');
INSERT INTO petbreeds VALUES('American Eskimo', 'Dog');
INSERT INTO petbreeds VALUES('American Foxhound', 'Dog');
INSERT INTO petbreeds VALUES('American Hairless Terrier', 'Dog');
INSERT INTO petbreeds VALUES('American Pit Bull Terrier', 'Dog');
INSERT INTO petbreeds VALUES('American Staffordshire Terrier', 'Dog');
INSERT INTO petbreeds VALUES('American Water Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('Anatolian Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Andalusian Hound', 'Dog');
INSERT INTO petbreeds VALUES('Appenzeller Sennenhund', 'Dog');
INSERT INTO petbreeds VALUES('Ariege Pointer', 'Dog');
INSERT INTO petbreeds VALUES('Ariegeois', 'Dog');
INSERT INTO petbreeds VALUES('Armant', 'Dog');
INSERT INTO petbreeds VALUES('Armenian Gampr', 'Dog');
INSERT INTO petbreeds VALUES('Artois Hound', 'Dog');
INSERT INTO petbreeds VALUES('Australian Cattle', 'Dog');
INSERT INTO petbreeds VALUES('Australian Kelpie', 'Dog');
INSERT INTO petbreeds VALUES('Australian Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Australian Silky Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Australian Stumpy Tail Cattle', 'Dog');
INSERT INTO petbreeds VALUES('Australian Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Austrian Black and Tan Hound', 'Dog');
INSERT INTO petbreeds VALUES('Austrian Pinscher', 'Dog');
INSERT INTO petbreeds VALUES('Azawakh', 'Dog');
INSERT INTO petbreeds VALUES('Barbet', 'Dog');
INSERT INTO petbreeds VALUES('Basenji', 'Dog');
INSERT INTO petbreeds VALUES('Basque Ratter', 'Dog');
INSERT INTO petbreeds VALUES('Basque Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Basset Bleu de Gascogne', 'Dog');
INSERT INTO petbreeds VALUES('Basset Fauve de Bretagne', 'Dog');
INSERT INTO petbreeds VALUES('Basset Hound', 'Dog');
INSERT INTO petbreeds VALUES('Bavarian Mountain Hound', 'Dog');
INSERT INTO petbreeds VALUES('Beagle', 'Dog');
INSERT INTO petbreeds VALUES('Beagle-Harrier', 'Dog');
INSERT INTO petbreeds VALUES('Bearded Collie', 'Dog');
INSERT INTO petbreeds VALUES('Beauceron', 'Dog');
INSERT INTO petbreeds VALUES('Bedlington Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Belgian Shepherd Dog (Groenendael)', 'Dog');
INSERT INTO petbreeds VALUES('Belgian Shepherd Dog (Laekenois)', 'Dog');
INSERT INTO petbreeds VALUES('Belgian Shepherd Dog (Malinois)', 'Dog');
INSERT INTO petbreeds VALUES('Belgian Shepherd Dog (Tervuren)', 'Dog');
INSERT INTO petbreeds VALUES('Anglo-Français de Petite VÃ©nerie', 'Dog');
INSERT INTO petbreeds VALUES('Alano Espanol', 'Dog');
INSERT INTO petbreeds VALUES('Basset Artésien Normand', 'Dog');
INSERT INTO petbreeds VALUES('Basset Griffon Vendéen, Grand', 'Dog');
INSERT INTO petbreeds VALUES('Basset Griffon Vendéen, Petit', 'Dog');
INSERT INTO petbreeds VALUES('Bergamasco Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Berger Blanc Suisse', 'Dog');
INSERT INTO petbreeds VALUES('Berger Picard', 'Dog');
INSERT INTO petbreeds VALUES('Bernese Mountain', 'Dog');
INSERT INTO petbreeds VALUES('Billy', 'Dog');
INSERT INTO petbreeds VALUES('Black and Tan Coonhound', 'Dog');
INSERT INTO petbreeds VALUES('Black and Tan Virginia Foxhound', 'Dog');
INSERT INTO petbreeds VALUES('Black Norwegian Elkhound', 'Dog');
INSERT INTO petbreeds VALUES('Black Russian Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Black Mouth Cur', 'Dog');
INSERT INTO petbreeds VALUES('Bleu de Gascogne, Grand', 'Dog');
INSERT INTO petbreeds VALUES('Bleu de Gascogne, Petit', 'Dog');
INSERT INTO petbreeds VALUES('Bloodhound', 'Dog');
INSERT INTO petbreeds VALUES('Blue Heeler', 'Dog');
INSERT INTO petbreeds VALUES('Blue Lacy', 'Dog');
INSERT INTO petbreeds VALUES('Blue Paul Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Blue Picardy Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('Bluetick Coonhound', 'Dog');
INSERT INTO petbreeds VALUES('Boerboel', 'Dog');
INSERT INTO petbreeds VALUES('Bohemian Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Bolognese', 'Dog');
INSERT INTO petbreeds VALUES('Border Collie', 'Dog');
INSERT INTO petbreeds VALUES('Border Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Borzoi', 'Dog');
INSERT INTO petbreeds VALUES('Bosnian Coarse-haired Hound', 'Dog');
INSERT INTO petbreeds VALUES('Boston Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Bouvier des Ardennes', 'Dog');
INSERT INTO petbreeds VALUES('Bouvier des Flandres', 'Dog');
INSERT INTO petbreeds VALUES('Boxer', 'Dog');
INSERT INTO petbreeds VALUES('Boykin Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('Bracco Italiano', 'Dog');
INSERT INTO petbreeds VALUES('Braque d''Auvergne', 'Dog');
INSERT INTO petbreeds VALUES('Braque du Bourbonnais', 'Dog');
INSERT INTO petbreeds VALUES('Braque du Puy', 'Dog');
INSERT INTO petbreeds VALUES('Braque Francais', 'Dog');
INSERT INTO petbreeds VALUES('Braque Saint-Germain', 'Dog');
INSERT INTO petbreeds VALUES('Brazilian Dogo', 'Dog');
INSERT INTO petbreeds VALUES('Brazilian Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Briard', 'Dog');
INSERT INTO petbreeds VALUES('Brittany', 'Dog');
INSERT INTO petbreeds VALUES('Broholmer', 'Dog');
INSERT INTO petbreeds VALUES('Bruno Jura Hound', 'Dog');
INSERT INTO petbreeds VALUES('Bucovina Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Bull and Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Bull Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Bull Terrier (Miniature)', 'Dog');
INSERT INTO petbreeds VALUES('Bulldog', 'Dog');
INSERT INTO petbreeds VALUES('Bullenbeisser', 'Dog');
INSERT INTO petbreeds VALUES('Bullmastiff', 'Dog');
INSERT INTO petbreeds VALUES('Bully Kutta', 'Dog');
INSERT INTO petbreeds VALUES('Burgos Pointer', 'Dog');
INSERT INTO petbreeds VALUES('Canaan', 'Dog');
INSERT INTO petbreeds VALUES('Canadian Eskimo', 'Dog');
INSERT INTO petbreeds VALUES('Cane Corso', 'Dog');
INSERT INTO petbreeds VALUES('Cantabrian Water', 'Dog');
INSERT INTO petbreeds VALUES('Carolina', 'Dog');
INSERT INTO petbreeds VALUES('Carpathian Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Catahoula Leopard', 'Dog');
INSERT INTO petbreeds VALUES('Catalan Sheepdog', 'Dog');
INSERT INTO petbreeds VALUES('Caucasian Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Cavalier King Charles Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('Central Asian Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Cesky Fousek', 'Dog');
INSERT INTO petbreeds VALUES('Cesky Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Chesapeake Bay Retriever', 'Dog');
INSERT INTO petbreeds VALUES('Chien-gris', 'Dog');
INSERT INTO petbreeds VALUES('Chihuahua', 'Dog');
INSERT INTO petbreeds VALUES('Chilean Fox Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Chinese Chongqing', 'Dog');
INSERT INTO petbreeds VALUES('Chinese Crested', 'Dog');
INSERT INTO petbreeds VALUES('Chinese Imperial', 'Dog');
INSERT INTO petbreeds VALUES('Chinook', 'Dog');
INSERT INTO petbreeds VALUES('Chippiparai', 'Dog');
INSERT INTO petbreeds VALUES('Chow Chow', 'Dog');
INSERT INTO petbreeds VALUES('Cierny Sery', 'Dog');
INSERT INTO petbreeds VALUES('Cirneco dell''Etna', 'Dog');
INSERT INTO petbreeds VALUES('Clumber Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('Collie, Rough', 'Dog');
INSERT INTO petbreeds VALUES('Collie, Smooth', 'Dog');
INSERT INTO petbreeds VALUES('Combai', 'Dog');
INSERT INTO petbreeds VALUES('Cordoba Fighting', 'Dog');
INSERT INTO petbreeds VALUES('Coton de Tulear', 'Dog');
INSERT INTO petbreeds VALUES('Cretan Hound', 'Dog');
INSERT INTO petbreeds VALUES('Croatian Sheepdog', 'Dog');
INSERT INTO petbreeds VALUES('Cumberland Sheepdog', 'Dog');
INSERT INTO petbreeds VALUES('Curly-Coated Retriever', 'Dog');
INSERT INTO petbreeds VALUES('Cursinu', 'Dog');
INSERT INTO petbreeds VALUES('Czechoslovakian Wolfdog', 'Dog');
INSERT INTO petbreeds VALUES('Dalmatian', 'Dog');
INSERT INTO petbreeds VALUES('Dandie Dinmont Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Danish-Swedish Farmdog', 'Dog');
INSERT INTO petbreeds VALUES('Deutsche Bracke', 'Dog');
INSERT INTO petbreeds VALUES('Doberman Pinscher', 'Dog');
INSERT INTO petbreeds VALUES('Dogo Argentino', 'Dog');
INSERT INTO petbreeds VALUES('Dogo Cubano', 'Dog');
INSERT INTO petbreeds VALUES('Dogue de Bordeaux', 'Dog');
INSERT INTO petbreeds VALUES('Drentse Patrijshond', 'Dog');
INSERT INTO petbreeds VALUES('Drever', 'Dog');
INSERT INTO petbreeds VALUES('Dunker', 'Dog');
INSERT INTO petbreeds VALUES('Dutch Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Dutch Smoushond', 'Dog');
INSERT INTO petbreeds VALUES('East European Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Elo', 'Dog');
INSERT INTO petbreeds VALUES('English Cocker Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('English Foxhound', 'Dog');
INSERT INTO petbreeds VALUES('English Mastiff', 'Dog');
INSERT INTO petbreeds VALUES('English Setter', 'Dog');
INSERT INTO petbreeds VALUES('English Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('English Springer Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('English Toy Terrier (Black & Tan)', 'Dog');
INSERT INTO petbreeds VALUES('English Water Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('English White Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Entlebucher Mountain', 'Dog');
INSERT INTO petbreeds VALUES('Estonian Hound', 'Dog');
INSERT INTO petbreeds VALUES('Estrela Mountain', 'Dog');
INSERT INTO petbreeds VALUES('Eurasier', 'Dog');
INSERT INTO petbreeds VALUES('Eurohound', 'Dog');
INSERT INTO petbreeds VALUES('Fila Brasileiro', 'Dog');
INSERT INTO petbreeds VALUES('Finnish Hound', 'Dog');
INSERT INTO petbreeds VALUES('Finnish Lapphund', 'Dog');
INSERT INTO petbreeds VALUES('Finnish Spitz', 'Dog');
INSERT INTO petbreeds VALUES('Flat-Coated Retriever', 'Dog');
INSERT INTO petbreeds VALUES('Fox Terrier (Smooth)', 'Dog');
INSERT INTO petbreeds VALUES('Fox Terrier, Wire', 'Dog');
INSERT INTO petbreeds VALUES('French Brittany', 'Dog');
INSERT INTO petbreeds VALUES('French Bulldog', 'Dog');
INSERT INTO petbreeds VALUES('French Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('Galician Cattle', 'Dog');
INSERT INTO petbreeds VALUES('Garafian Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Gascon Saintongeois', 'Dog');
INSERT INTO petbreeds VALUES('Georgian Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('German Longhaired Pointer', 'Dog');
INSERT INTO petbreeds VALUES('German Pinscher', 'Dog');
INSERT INTO petbreeds VALUES('German Roughhaired Pointer', 'Dog');
INSERT INTO petbreeds VALUES('German Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('German Shorthaired Pointer', 'Dog');
INSERT INTO petbreeds VALUES('German Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('German Spitz', 'Dog');
INSERT INTO petbreeds VALUES('German Wirehaired Pointer', 'Dog');
INSERT INTO petbreeds VALUES('Giant Schnauzer', 'Dog');
INSERT INTO petbreeds VALUES('Glen of Imaal Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Golden Retriever', 'Dog');
INSERT INTO petbreeds VALUES('Gordon Setter', 'Dog');
INSERT INTO petbreeds VALUES('Cão de Castro Laboreiro', 'Dog');
INSERT INTO petbreeds VALUES('Cão de Gado Transmontano', 'Dog');
INSERT INTO petbreeds VALUES('Cão Fila de São Miguel', 'Dog');
INSERT INTO petbreeds VALUES('Chien Français Blanc et Noir', 'Dog');
INSERT INTO petbreeds VALUES('Chien Français Blanc et Orange', 'Dog');
INSERT INTO petbreeds VALUES('Chien Français Tricolore', 'Dog');
INSERT INTO petbreeds VALUES('Bichon Frisé', 'Dog');
INSERT INTO petbreeds VALUES('Briquet Griffon Vendéen', 'Dog');
INSERT INTO petbreeds VALUES('Galgo Espanol', 'Dog');
INSERT INTO petbreeds VALUES('Great Dane', 'Dog');
INSERT INTO petbreeds VALUES('Great Pyrenees', 'Dog');
INSERT INTO petbreeds VALUES('Greater Swiss Mountain', 'Dog');
INSERT INTO petbreeds VALUES('Greek Harehound', 'Dog');
INSERT INTO petbreeds VALUES('Greenland', 'Dog');
INSERT INTO petbreeds VALUES('Greyhound', 'Dog');
INSERT INTO petbreeds VALUES('Griffon Bleu de Gascogne', 'Dog');
INSERT INTO petbreeds VALUES('Griffon Bruxellois', 'Dog');
INSERT INTO petbreeds VALUES('Griffon Fauve de Bretagne', 'Dog');
INSERT INTO petbreeds VALUES('Griffon Nivernais', 'Dog');
INSERT INTO petbreeds VALUES('Guatemalan Dogo', 'Dog');
INSERT INTO petbreeds VALUES('Hanover Hound', 'Dog');
INSERT INTO petbreeds VALUES('Hare Indian', 'Dog');
INSERT INTO petbreeds VALUES('Harrier', 'Dog');
INSERT INTO petbreeds VALUES('Havanese', 'Dog');
INSERT INTO petbreeds VALUES('Hawaiian Poi', 'Dog');
INSERT INTO petbreeds VALUES('Himalayan Sheepdog', 'Dog');
INSERT INTO petbreeds VALUES('Hokkaido', 'Dog');
INSERT INTO petbreeds VALUES('Hortaya Borzaya', 'Dog');
INSERT INTO petbreeds VALUES('Hovawart', 'Dog');
INSERT INTO petbreeds VALUES('Huntaway', 'Dog');
INSERT INTO petbreeds VALUES('Hygenhund', 'Dog');
INSERT INTO petbreeds VALUES('Icelandic Sheepdog', 'Dog');
INSERT INTO petbreeds VALUES('Indian pariah', 'Dog');
INSERT INTO petbreeds VALUES('Indian Spitz', 'Dog');
INSERT INTO petbreeds VALUES('Irish Red and White Setter', 'Dog');
INSERT INTO petbreeds VALUES('Irish Setter', 'Dog');
INSERT INTO petbreeds VALUES('Irish Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Irish Water Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('Irish Wolfhound', 'Dog');
INSERT INTO petbreeds VALUES('Istrian Coarse-haired Hound', 'Dog');
INSERT INTO petbreeds VALUES('Istrian Shorthaired Hound', 'Dog');
INSERT INTO petbreeds VALUES('Italian Greyhound', 'Dog');
INSERT INTO petbreeds VALUES('Jagdterrier', 'Dog');
INSERT INTO petbreeds VALUES('Japanese Chin', 'Dog');
INSERT INTO petbreeds VALUES('Japanese Spitz', 'Dog');
INSERT INTO petbreeds VALUES('Japanese Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Kai Ken', 'Dog');
INSERT INTO petbreeds VALUES('Kangal', 'Dog');
INSERT INTO petbreeds VALUES('Kanni', 'Dog');
INSERT INTO petbreeds VALUES('Karakachan', 'Dog');
INSERT INTO petbreeds VALUES('Karelian Bear', 'Dog');
INSERT INTO petbreeds VALUES('Karst Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Keeshond', 'Dog');
INSERT INTO petbreeds VALUES('Kerry Beagle', 'Dog');
INSERT INTO petbreeds VALUES('Kerry Blue Terrier', 'Dog');
INSERT INTO petbreeds VALUES('King Charles Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('King Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Kintamani', 'Dog');
INSERT INTO petbreeds VALUES('Kishu Ken', 'Dog');
INSERT INTO petbreeds VALUES('Komondor', 'Dog');
INSERT INTO petbreeds VALUES('Kooikerhondje', 'Dog');
INSERT INTO petbreeds VALUES('Koolie', 'Dog');
INSERT INTO petbreeds VALUES('Korean Jindo', 'Dog');
INSERT INTO petbreeds VALUES('Kumaon Mastiff', 'Dog');
INSERT INTO petbreeds VALUES('Kunming Wolfdog', 'Dog');
INSERT INTO petbreeds VALUES('Kuvasz', 'Dog');
INSERT INTO petbreeds VALUES('Kyi-Leo', 'Dog');
INSERT INTO petbreeds VALUES('Labrador Retriever', 'Dog');
INSERT INTO petbreeds VALUES('Lagotto Romagnolo', 'Dog');
INSERT INTO petbreeds VALUES('Lakeland Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Lancashire Heeler', 'Dog');
INSERT INTO petbreeds VALUES('Landseer', 'Dog');
INSERT INTO petbreeds VALUES('Lapponian Herder', 'Dog');
INSERT INTO petbreeds VALUES('Leonberger', 'Dog');
INSERT INTO petbreeds VALUES('Lhasa Apso', 'Dog');
INSERT INTO petbreeds VALUES('Lithuanian Hound', 'Dog');
INSERT INTO petbreeds VALUES('Löwchen', 'Dog');
INSERT INTO petbreeds VALUES('Mackenzie River Husky', 'Dog');
INSERT INTO petbreeds VALUES('Mahratta Greyhound', 'Dog');
INSERT INTO petbreeds VALUES('Majorca Ratter', 'Dog');
INSERT INTO petbreeds VALUES('Majorca Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Maltese', 'Dog');
INSERT INTO petbreeds VALUES('Manchester Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Maremma Sheepdog', 'Dog');
INSERT INTO petbreeds VALUES('McNab', 'Dog');
INSERT INTO petbreeds VALUES('Mexican Hairless', 'Dog');
INSERT INTO petbreeds VALUES('Miniature Australian Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Miniature American Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Miniature Fox Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Miniature Pinscher', 'Dog');
INSERT INTO petbreeds VALUES('Miniature Schnauzer', 'Dog');
INSERT INTO petbreeds VALUES('Miniature Shar Pei', 'Dog');
INSERT INTO petbreeds VALUES('Mioritic', 'Dog');
INSERT INTO petbreeds VALUES('Molossus', 'Dog');
INSERT INTO petbreeds VALUES('Molossus of Epirus', 'Dog');
INSERT INTO petbreeds VALUES('Montenegrin Mountain Hound', 'Dog');
INSERT INTO petbreeds VALUES('Moscow Watchdog', 'Dog');
INSERT INTO petbreeds VALUES('Moscow Water', 'Dog');
INSERT INTO petbreeds VALUES('Mountain Cur', 'Dog');
INSERT INTO petbreeds VALUES('Mucuchies', 'Dog');
INSERT INTO petbreeds VALUES('Mudhol Hound', 'Dog');
INSERT INTO petbreeds VALUES('Mudi', 'Dog');
INSERT INTO petbreeds VALUES('Münsterländer, Large', 'Dog');
INSERT INTO petbreeds VALUES('Münsterländer, Small', 'Dog');
INSERT INTO petbreeds VALUES('Newfoundland', 'Dog');
INSERT INTO petbreeds VALUES('New Zealand Heading', 'Dog');
INSERT INTO petbreeds VALUES('Norfolk Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('Norfolk Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Norrbottenspets', 'Dog');
INSERT INTO petbreeds VALUES('North Country Beagle', 'Dog');
INSERT INTO petbreeds VALUES('Northern Inuit', 'Dog');
INSERT INTO petbreeds VALUES('Norwegian Buhund', 'Dog');
INSERT INTO petbreeds VALUES('Norwegian Elkhound', 'Dog');
INSERT INTO petbreeds VALUES('Norwegian Lundehund', 'Dog');
INSERT INTO petbreeds VALUES('Norwich Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Nova Scotia Duck-Tolling Retriever', 'Dog');
INSERT INTO petbreeds VALUES('Old Danish Pointer', 'Dog');
INSERT INTO petbreeds VALUES('Old English Sheepdog', 'Dog');
INSERT INTO petbreeds VALUES('Old English Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Old German Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Old Time Farm Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Olde English Bulldogge', 'Dog');
INSERT INTO petbreeds VALUES('Otterhound', 'Dog');
INSERT INTO petbreeds VALUES('Pandikona Hunting', 'Dog');
INSERT INTO petbreeds VALUES('Paisley Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Papillon', 'Dog');
INSERT INTO petbreeds VALUES('Parson Russell Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Patterdale Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Pekingese', 'Dog');
INSERT INTO petbreeds VALUES('Perro de Presa Canario', 'Dog');
INSERT INTO petbreeds VALUES('Perro de Presa Mallorquin', 'Dog');
INSERT INTO petbreeds VALUES('Peruvian Hairless', 'Dog');
INSERT INTO petbreeds VALUES('Pharaoh Hound', 'Dog');
INSERT INTO petbreeds VALUES('Phu Quoc Ridgeback', 'Dog');
INSERT INTO petbreeds VALUES('Picardy Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('Plummer Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Plott Hound', 'Dog');
INSERT INTO petbreeds VALUES('Podenco Canario', 'Dog');
INSERT INTO petbreeds VALUES('Pointer', 'Dog');
INSERT INTO petbreeds VALUES('Poitevin', 'Dog');
INSERT INTO petbreeds VALUES('Polish Greyhound', 'Dog');
INSERT INTO petbreeds VALUES('Polish Hound', 'Dog');
INSERT INTO petbreeds VALUES('Polish Hunting', 'Dog');
INSERT INTO petbreeds VALUES('Polish Lowland Sheepdog', 'Dog');
INSERT INTO petbreeds VALUES('Polish Tatra Sheepdog', 'Dog');
INSERT INTO petbreeds VALUES('Pomeranian', 'Dog');
INSERT INTO petbreeds VALUES('Pont-Audemer Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('Poodle', 'Dog');
INSERT INTO petbreeds VALUES('Porcelaine', 'Dog');
INSERT INTO petbreeds VALUES('Portuguese Podengo', 'Dog');
INSERT INTO petbreeds VALUES('Portuguese Pointer', 'Dog');
INSERT INTO petbreeds VALUES('Portuguese Water', 'Dog');
INSERT INTO petbreeds VALUES('Posavac Hound', 'Dog');
INSERT INTO petbreeds VALUES('Pudelpointer', 'Dog');
INSERT INTO petbreeds VALUES('Pug', 'Dog');
INSERT INTO petbreeds VALUES('Puli', 'Dog');
INSERT INTO petbreeds VALUES('Pumi', 'Dog');
INSERT INTO petbreeds VALUES('Pungsan', 'Dog');
INSERT INTO petbreeds VALUES('Grand Anglo-Français Blanc et Noir', 'Dog');
INSERT INTO petbreeds VALUES('Grand Anglo-Français Blanc et Orange', 'Dog');
INSERT INTO petbreeds VALUES('Grand Griffon Vendéen', 'Dog');
INSERT INTO petbreeds VALUES('Jämthund', 'Dog');
INSERT INTO petbreeds VALUES('Kromfohrländer', 'Dog');
INSERT INTO petbreeds VALUES('Pyrenean Mastiff', 'Dog');
INSERT INTO petbreeds VALUES('Pyrenean Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Rajapalayam', 'Dog');
INSERT INTO petbreeds VALUES('Rampur Greyhound', 'Dog');
INSERT INTO petbreeds VALUES('Rastreador Brasileiro', 'Dog');
INSERT INTO petbreeds VALUES('Ratonero Bodeguero Andaluz', 'Dog');
INSERT INTO petbreeds VALUES('Ratonero Murciano de Huerta', 'Dog');
INSERT INTO petbreeds VALUES('Ratonero Valenciano', 'Dog');
INSERT INTO petbreeds VALUES('Rat Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Redbone Coonhound', 'Dog');
INSERT INTO petbreeds VALUES('Rhodesian Ridgeback', 'Dog');
INSERT INTO petbreeds VALUES('Rottweiler', 'Dog');
INSERT INTO petbreeds VALUES('Russian Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('Russian Toy', 'Dog');
INSERT INTO petbreeds VALUES('Russian Tracker', 'Dog');
INSERT INTO petbreeds VALUES('Russo-European Laika', 'Dog');
INSERT INTO petbreeds VALUES('Russell Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Sabueso Espanol', 'Dog');
INSERT INTO petbreeds VALUES('Sabueso fino Colombiano', 'Dog');
INSERT INTO petbreeds VALUES('Saint-Usuge Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('Sakhalin Husky', 'Dog');
INSERT INTO petbreeds VALUES('Saluki', 'Dog');
INSERT INTO petbreeds VALUES('Samoyed', 'Dog');
INSERT INTO petbreeds VALUES('Sapsali', 'Dog');
INSERT INTO petbreeds VALUES('Šarplaninac', 'Dog');
INSERT INTO petbreeds VALUES('Schapendoes', 'Dog');
INSERT INTO petbreeds VALUES('Schillerstövare', 'Dog');
INSERT INTO petbreeds VALUES('Schipperke', 'Dog');
INSERT INTO petbreeds VALUES('Standard Schnauzer', 'Dog');
INSERT INTO petbreeds VALUES('Schweizer Laufhund', 'Dog');
INSERT INTO petbreeds VALUES('Schweizerischer Niederlaufhund', 'Dog');
INSERT INTO petbreeds VALUES('Scotch Collie', 'Dog');
INSERT INTO petbreeds VALUES('Scottish Deerhound', 'Dog');
INSERT INTO petbreeds VALUES('Scottish Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Sealyham Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Segugio Italiano', 'Dog');
INSERT INTO petbreeds VALUES('Seppala Siberian Sleddog', 'Dog');
INSERT INTO petbreeds VALUES('Serbian Hound', 'Dog');
INSERT INTO petbreeds VALUES('Serbian Tricolour Hound', 'Dog');
INSERT INTO petbreeds VALUES('Seskar Seal', 'Dog');
INSERT INTO petbreeds VALUES('Shar Pei', 'Dog');
INSERT INTO petbreeds VALUES('Shetland Sheepdog', 'Dog');
INSERT INTO petbreeds VALUES('Shiba Inu', 'Dog');
INSERT INTO petbreeds VALUES('Shih Tzu', 'Dog');
INSERT INTO petbreeds VALUES('Shikoku', 'Dog');
INSERT INTO petbreeds VALUES('Shiloh Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Siberian Husky', 'Dog');
INSERT INTO petbreeds VALUES('Silken Windhound', 'Dog');
INSERT INTO petbreeds VALUES('Sinhala Hound', 'Dog');
INSERT INTO petbreeds VALUES('Skye Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Sloughi', 'Dog');
INSERT INTO petbreeds VALUES('Slovak Cuvac', 'Dog');
INSERT INTO petbreeds VALUES('Slovakian Rough-haired Pointer', 'Dog');
INSERT INTO petbreeds VALUES('Slovenský Kopov', 'Dog');
INSERT INTO petbreeds VALUES('Smålandsstövare', 'Dog');
INSERT INTO petbreeds VALUES('Small Greek Domestic', 'Dog');
INSERT INTO petbreeds VALUES('Soft-Coated Wheaten Terrier', 'Dog');
INSERT INTO petbreeds VALUES('South Russian Ovcharka', 'Dog');
INSERT INTO petbreeds VALUES('Southern Hound', 'Dog');
INSERT INTO petbreeds VALUES('Spanish Mastiff', 'Dog');
INSERT INTO petbreeds VALUES('Spanish Water', 'Dog');
INSERT INTO petbreeds VALUES('Spinone Italiano', 'Dog');
INSERT INTO petbreeds VALUES('Sporting Lucas Terrier', 'Dog');
INSERT INTO petbreeds VALUES('St. Bernard', 'Dog');
INSERT INTO petbreeds VALUES('St. John''s water', 'Dog');
INSERT INTO petbreeds VALUES('Stabyhoun', 'Dog');
INSERT INTO petbreeds VALUES('Staffordshire Bull Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Stephens Cur', 'Dog');
INSERT INTO petbreeds VALUES('Styrian Coarse-haired Hound', 'Dog');
INSERT INTO petbreeds VALUES('Sussex Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('Swedish Lapphund', 'Dog');
INSERT INTO petbreeds VALUES('Swedish Vallhund', 'Dog');
INSERT INTO petbreeds VALUES('Taigan', 'Dog');
INSERT INTO petbreeds VALUES('Taiwan', 'Dog');
INSERT INTO petbreeds VALUES('Talbot', 'Dog');
INSERT INTO petbreeds VALUES('Tamaskan', 'Dog');
INSERT INTO petbreeds VALUES('Teddy Roosevelt Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Telomian', 'Dog');
INSERT INTO petbreeds VALUES('Tenterfield Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Terceira Mastiff', 'Dog');
INSERT INTO petbreeds VALUES('Thai Bangkaew', 'Dog');
INSERT INTO petbreeds VALUES('Thai Ridgeback', 'Dog');
INSERT INTO petbreeds VALUES('Tibetan Mastiff', 'Dog');
INSERT INTO petbreeds VALUES('Tibetan Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('Tibetan Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Tornjak', 'Dog');
INSERT INTO petbreeds VALUES('Tosa', 'Dog');
INSERT INTO petbreeds VALUES('Toy Bulldog', 'Dog');
INSERT INTO petbreeds VALUES('Toy Fox Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Toy Manchester Terrier', 'Dog');
INSERT INTO petbreeds VALUES('Toy Trawler Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('Transylvanian Hound', 'Dog');
INSERT INTO petbreeds VALUES('Treeing Cur', 'Dog');
INSERT INTO petbreeds VALUES('Treeing Tennessee Brindle', 'Dog');
INSERT INTO petbreeds VALUES('Treeing Walker Coonhound', 'Dog');
INSERT INTO petbreeds VALUES('Trigg Hound', 'Dog');
INSERT INTO petbreeds VALUES('Tweed Water Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('Tyrolean Hound', 'Dog');
INSERT INTO petbreeds VALUES('Uruguayan Cimarron', 'Dog');
INSERT INTO petbreeds VALUES('Valencian Ratter', 'Dog');
INSERT INTO petbreeds VALUES('Vanjari Hound', 'Dog');
INSERT INTO petbreeds VALUES('Villano de Las Encartaciones', 'Dog');
INSERT INTO petbreeds VALUES('Vizsla', 'Dog');
INSERT INTO petbreeds VALUES('Volpino Italiano', 'Dog');
INSERT INTO petbreeds VALUES('Welsh Corgi, Cardigan', 'Dog');
INSERT INTO petbreeds VALUES('Welsh Corgi, Pembroke', 'Dog');
INSERT INTO petbreeds VALUES('Welsh Sheepdog', 'Dog');
INSERT INTO petbreeds VALUES('Welsh Springer Spaniel', 'Dog');
INSERT INTO petbreeds VALUES('Welsh Terrier', 'Dog');
INSERT INTO petbreeds VALUES('West Highland White Terrier', 'Dog');
INSERT INTO petbreeds VALUES('West Siberian Laika', 'Dog');
INSERT INTO petbreeds VALUES('Westphalian Dachsbracke', 'Dog');
INSERT INTO petbreeds VALUES('Wetterhoun', 'Dog');
INSERT INTO petbreeds VALUES('Whippet', 'Dog');
INSERT INTO petbreeds VALUES('White Shepherd', 'Dog');
INSERT INTO petbreeds VALUES('Wirehaired Pointing Griffon', 'Dog');
INSERT INTO petbreeds VALUES('Wirehaired Vizsla', 'Dog');
INSERT INTO petbreeds VALUES('Cão da Serra de Aires', 'Dog');
INSERT INTO petbreeds VALUES('Grand Anglo-Français Tricolore', 'Dog');
INSERT INTO petbreeds VALUES('Gran Mastín de Borínquen', 'Dog');