INSERT INTO petbreeds VALUES('Abyssinian','Cat');
INSERT INTO petbreeds VALUES('Aegean','Cat');
INSERT INTO petbreeds VALUES('American Curl','Cat');
INSERT INTO petbreeds VALUES('American Bobtail','Cat');
INSERT INTO petbreeds VALUES('American Shorthair','Cat');
INSERT INTO petbreeds VALUES('American Wirehair','Cat');
INSERT INTO petbreeds VALUES('Arabian Mau','Cat');
INSERT INTO petbreeds VALUES('Australian Mist','Cat');
INSERT INTO petbreeds VALUES('Asian','Cat');
INSERT INTO petbreeds VALUES('Asian Semi-longhair','Cat');
INSERT INTO petbreeds VALUES('Balinese','Cat');
INSERT INTO petbreeds VALUES('Bambino','Cat');
INSERT INTO petbreeds VALUES('Bengal','Cat');
INSERT INTO petbreeds VALUES('Birman','Cat');
INSERT INTO petbreeds VALUES('Bombay','Cat');
INSERT INTO petbreeds VALUES('Brazilian Shorthair','Cat');
INSERT INTO petbreeds VALUES('British Semi-longhair','Cat');
INSERT INTO petbreeds VALUES('British Shorthair','Cat');
INSERT INTO petbreeds VALUES('British Longhair','Cat');
INSERT INTO petbreeds VALUES('Burmese','Cat');
INSERT INTO petbreeds VALUES('Burmilla','Cat');
INSERT INTO petbreeds VALUES('California Spangled','Cat');
INSERT INTO petbreeds VALUES('Chantilly-Tiffany','Cat');
INSERT INTO petbreeds VALUES('Chartreux','Cat');
INSERT INTO petbreeds VALUES('Chausie','Cat');
INSERT INTO petbreeds VALUES('Cheetoh','Cat');
INSERT INTO petbreeds VALUES('Colorpoint Shorthair','Cat');
INSERT INTO petbreeds VALUES('Cornish Rex','Cat');
INSERT INTO petbreeds VALUES('Cymric','Cat');
INSERT INTO petbreeds VALUES('Cyprus','Cat');
INSERT INTO petbreeds VALUES('Devon Rex','Cat');
INSERT INTO petbreeds VALUES('Donskoy','Cat');
INSERT INTO petbreeds VALUES('Dragon Li','Cat');
INSERT INTO petbreeds VALUES('Dwarf cat','Cat');
INSERT INTO petbreeds VALUES('Egyptian Mau','Cat');
INSERT INTO petbreeds VALUES('European Shorthair','Cat');
INSERT INTO petbreeds VALUES('Exotic Shorthair','Cat');
INSERT INTO petbreeds VALUES('Foldex','Cat');
INSERT INTO petbreeds VALUES('German Rex','Cat');
INSERT INTO petbreeds VALUES('Havana Brown','Cat');
INSERT INTO petbreeds VALUES('Highlander','Cat');
INSERT INTO petbreeds VALUES('Himalayan','Cat');
INSERT INTO petbreeds VALUES('Japanese Bobtail','Cat');
INSERT INTO petbreeds VALUES('Javanese','Cat');
INSERT INTO petbreeds VALUES('Karelian Bobtail','Cat');
INSERT INTO petbreeds VALUES('Khao Manee','Cat');
INSERT INTO petbreeds VALUES('Korat','Cat');
INSERT INTO petbreeds VALUES('Korean Bobtail','Cat');
INSERT INTO petbreeds VALUES('Korn Ja','Cat');
INSERT INTO petbreeds VALUES('Kurilian Bobtail','Cat');
INSERT INTO petbreeds VALUES('LaPerm','Cat');
INSERT INTO petbreeds VALUES('Lykoi','Cat');
INSERT INTO petbreeds VALUES('Maine Coon','Cat');
INSERT INTO petbreeds VALUES('Manx','Cat');
INSERT INTO petbreeds VALUES('Mekong Bobtail','Cat');
INSERT INTO petbreeds VALUES('Minskin','Cat');
INSERT INTO petbreeds VALUES('Munchkin','Cat');
INSERT INTO petbreeds VALUES('Nebelung','Cat');
INSERT INTO petbreeds VALUES('Napoleon','Cat');
INSERT INTO petbreeds VALUES('Norwegian Forest cat','Cat');
INSERT INTO petbreeds VALUES('Ocicat','Cat');
INSERT INTO petbreeds VALUES('Ojos Azules','Cat');
INSERT INTO petbreeds VALUES('Oregon Rex','Cat');
INSERT INTO petbreeds VALUES('Oriental Bicolor','Cat');
INSERT INTO petbreeds VALUES('Oriental Shorthair','Cat');
INSERT INTO petbreeds VALUES('Oriental Longhair','Cat');
INSERT INTO petbreeds VALUES('PerFold','Cat');
INSERT INTO petbreeds VALUES('Persian (Modern Persian)','Cat');
INSERT INTO petbreeds VALUES('Persian (Traditional Persian)','Cat');
INSERT INTO petbreeds VALUES('Peterbald','Cat');
INSERT INTO petbreeds VALUES('Pixie-bob','Cat');
INSERT INTO petbreeds VALUES('Raas','Cat');
INSERT INTO petbreeds VALUES('Ragamuffin','Cat');
INSERT INTO petbreeds VALUES('Ragdoll','Cat');
INSERT INTO petbreeds VALUES('Russian Blue','Cat');
INSERT INTO petbreeds VALUES('Russian White, Black and Tabby','Cat');
INSERT INTO petbreeds VALUES('Sam Sawet','Cat');
INSERT INTO petbreeds VALUES('Savannah','Cat');
INSERT INTO petbreeds VALUES('Scottish Fold','Cat');
INSERT INTO petbreeds VALUES('Selkirk Rex','Cat');
INSERT INTO petbreeds VALUES('Serengeti','Cat');
INSERT INTO petbreeds VALUES('Serrade petit','Cat');
INSERT INTO petbreeds VALUES('Siamese','Cat');
INSERT INTO petbreeds VALUES('Siberian','Cat');
INSERT INTO petbreeds VALUES('Singapura','Cat');
INSERT INTO petbreeds VALUES('Snowshoe','Cat');
INSERT INTO petbreeds VALUES('Sokoke','Cat');
INSERT INTO petbreeds VALUES('Somali','Cat');
INSERT INTO petbreeds VALUES('Sphynx','Cat');
INSERT INTO petbreeds VALUES('Suphalak','Cat');
INSERT INTO petbreeds VALUES('Thai','Cat');
INSERT INTO petbreeds VALUES('Thai Lilac','Cat');
INSERT INTO petbreeds VALUES('Tonkinese','Cat');
INSERT INTO petbreeds VALUES('Toyger','Cat');
INSERT INTO petbreeds VALUES('Turkish Angora','Cat');
INSERT INTO petbreeds VALUES('Turkish Van','Cat');
INSERT INTO petbreeds VALUES('Ukrainian Levkoy','Cat');