insert into pets (name, id, typename, breedname, age, gender) values ('Ketti', 508, 'Cat', 'Colorpoint Shorthair', 2, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Leila', 721, 'Cat', 'Ukrainian Levkoy', 10, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Ninetta', 902, 'Cat', 'Napoleon', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Harri', 906, 'Cat', 'Singapura', 16, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Antoinette', 1136, 'Cat', 'Serrade petit', 4, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Clari', 1315, 'Cat', 'Singapura', 19, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Rozelle', 1313, 'Cat', 'American Shorthair', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Marline', 705, 'Cat', 'Australian Mist', 1, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Zelda', 553, 'Cat', 'Abyssinian', 1, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Shandee', 492, 'Cat', 'Burmese', 20, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Debbie', 640, 'Cat', 'Mekong Bobtail', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Bunni', 935, 'Cat', 'Cyprus', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Carlynn', 647, 'Cat', 'Bengal', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Mirabelle', 432, 'Cat', 'Foldex', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Allis', 483, 'Cat', 'Oriental Shorthair', 16, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Devon', 454, 'Cat', 'Tonkinese', 16, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Merrielle', 629, 'Cat', 'Snowshoe', 1, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Sofie', 918, 'Cat', 'Sam Sawet', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Ameline', 977, 'Cat', 'Birman', 16, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Nadeen', 766, 'Cat', 'Serengeti', 15, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Lynda', 461, 'Cat', 'Dwarf cat', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Melisande', 984, 'Cat', 'American Shorthair', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Tiffany', 514, 'Cat', 'Munchkin', 1, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Sukey', 467, 'Cat', 'British Longhair', 15, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Lynsey', 711, 'Cat', 'Ocicat', 2, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Latrena', 1015, 'Cat', 'American Wirehair', 15, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Pietra', 595, 'Cat', 'Selkirk Rex', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Shirline', 825, 'Cat', 'Oregon Rex', 8, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Bennie', 562, 'Cat', 'Savannah', 7, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Eba', 953, 'Cat', 'Pixie-bob', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Mab', 595, 'Cat', 'Norwegian Forest cat', 7, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Korney', 11, 'Cat', 'Arabian Mau', 10, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Claudia', 1197, 'Cat', 'Napoleon', 7, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Chanda', 514, 'Cat', 'Suphalak', 13, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Cathi', 802, 'Cat', 'Singapura', 14, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Chastity', 579, 'Cat', 'Sokoke', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Othella', 1213, 'Cat', 'Havana Brown', 7, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Herminia', 727, 'Cat', 'Foldex', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Dell', 507, 'Cat', 'Oriental Longhair', 16, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Doe', 591, 'Cat', 'Cheetoh', 4, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Jordanna', 802, 'Cat', 'Lykoi', 9, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Karena', 553, 'Cat', 'Devon Rex', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Jeralee', 958, 'Cat', 'Sphynx', 7, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Regine', 1007, 'Cat', 'British Semi-longhair', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Claudina', 695, 'Cat', 'Javanese', 11, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Francyne', 671, 'Cat', 'Dwarf cat', 10, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Matti', 1071, 'Cat', 'Sam Sawet', 11, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Leia', 593, 'Cat', 'Egyptian Mau', 16, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Felisha', 977, 'Cat', 'Ragamuffin', 19, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Reeta', 906, 'Cat', 'Colorpoint Shorthair', 12, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Alene', 1114, 'Cat', 'Turkish Van', 6, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Atlante', 1303, 'Cat', 'Burmese', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Isadora', 1225, 'Cat', 'Napoleon', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Dniren', 1301, 'Cat', 'Tonkinese', 8, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Jenna', 906, 'Cat', 'Dwarf cat', 3, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Stephine', 648, 'Cat', 'Napoleon', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Agnes', 647, 'Cat', 'Asian Semi-longhair', 8, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Deerdre', 1023, 'Cat', 'LaPerm', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Nert', 1315, 'Cat', 'Kurilian Bobtail', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Shelagh', 1078, 'Cat', 'European Shorthair', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Madelaine', 717, 'Cat', 'Siberian', 5, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Annamaria', 990, 'Cat', 'Russian Blue', 20, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Eunice', 789, 'Cat', 'Raas', 5, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Jehanna', 710, 'Cat', 'German Rex', 10, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Brita', 669, 'Cat', 'Kurilian Bobtail', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Glenda', 742, 'Cat', 'European Shorthair', 20, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Barbette', 648, 'Cat', 'Persian (Modern Persian)', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Lorene', 657, 'Cat', 'Somali', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Lorette', 624, 'Cat', 'Oriental Shorthair', 7, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Taryn', 1301, 'Cat', 'Cheetoh', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Gusti', 1114, 'Cat', 'LaPerm', 11, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Blondy', 1307, 'Cat', 'Aegean', 10, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Lucinda', 460, 'Cat', 'Bombay', 11, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Libbie', 861, 'Cat', 'Sam Sawet', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Allsun', 523, 'Cat', 'Scottish Fold', 6, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Kalila', 841, 'Cat', 'Arabian Mau', 2, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Bernadine', 861, 'Cat', 'Ojos Azules', 8, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Celestyna', 454, 'Cat', 'Sphynx', 7, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Abby', 21, 'Cat', 'Korn Ja', 7, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Lauryn', 432, 'Cat', 'American Wirehair', 7, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Merline', 568, 'Cat', 'Siberian', 16, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Joline', 994, 'Cat', 'American Bobtail', 2, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Marion', 450, 'Cat', 'Cheetoh', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Morena', 523, 'Cat', 'Javanese', 12, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Alida', 562, 'Cat', 'European Shorthair', 4, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Guinna', 620, 'Cat', 'Toyger', 8, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Emalia', 936, 'Cat', 'Turkish Van', 10, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Roxana', 1283, 'Cat', 'Ragamuffin', 8, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Gaye', 1036, 'Cat', 'Persian (Modern Persian)', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Cyndy', 656, 'Cat', 'Persian (Traditional Persian)', 4, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Tandy', 685, 'Cat', 'Siamese', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Naomi', 1029, 'Cat', 'Sokoke', 1, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Biddie', 912, 'Cat', 'Sam Sawet', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Marchelle', 1236, 'Cat', 'Burmilla', 12, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Evelina', 616, 'Cat', 'Minskin', 12, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Magdalena', 559, 'Cat', 'Nebelung', 1, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Audi', 1030, 'Cat', 'Serengeti', 13, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Aurie', 620, 'Cat', 'Bombay', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Alayne', 721, 'Cat', 'Sam Sawet', 15, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Fernande', 872, 'Cat', 'British Longhair', 15, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Joela', 942, 'Cat', 'Burmese', 6, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Shanie', 743, 'Cat', 'Manx', 2, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Vina', 855, 'Cat', 'Lykoi', 3, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Jillayne', 902, 'Cat', 'British Shorthair', 7, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Annamaria', 507, 'Cat', 'Norwegian Forest cat', 7, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Agace', 743, 'Cat', 'Oriental Longhair', 2, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Shayna', 918, 'Cat', 'Peterbald', 18, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Traci', 790, 'Cat', 'Selkirk Rex', 15, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Joly', 571, 'Cat', 'Havana Brown', 2, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Leeann', 507, 'Cat', 'Havana Brown', 16, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Waneta', 777, 'Cat', 'Serrade petit', 8, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Corinna', 1303, 'Cat', 'Chartreux', 1, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Raina', 506, 'Cat', 'Brazilian Shorthair', 19, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Lacey', 1235, 'Cat', 'Singapura', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Stephannie', 432, 'Cat', 'Aegean', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Britt', 725, 'Cat', 'German Rex', 14, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Carina', 1291, 'Cat', 'Bengal', 4, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Meghann', 1180, 'Cat', 'Cornish Rex', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Karlen', 1207, 'Cat', 'British Longhair', 8, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Georgina', 984, 'Cat', 'Singapura', 16, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Margaretha', 877, 'Cat', 'Siamese', 8, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Deloris', 919, 'Cat', 'Chantilly-Tiffany', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Helli', 958, 'Cat', 'Devon Rex', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Liane', 453, 'Cat', 'Serrade petit', 20, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Joceline', 855, 'Cat', 'Toyger', 6, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Annnora', 1283, 'Cat', 'Birman', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Veronike', 1331, 'Cat', 'Dragon Li', 19, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Batsheva', 750, 'Cat', 'American Shorthair', 12, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Daveta', 942, 'Cat', 'Dragon Li', 2, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Adrianne', 1225, 'Cat', 'Norwegian Forest cat', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Harriott', 1265, 'Cat', 'Bambino', 12, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Sarene', 782, 'Cat', 'Korat', 20, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Davine', 790, 'Cat', 'LaPerm', 6, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Kelley', 859, 'Cat', 'American Shorthair', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Hesther', 753, 'Cat', 'Abyssinian', 8, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Rozamond', 629, 'Cat', 'Foldex', 12, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Arleyne', 790, 'Cat', 'Napoleon', 8, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Merridie', 953, 'Cat', 'Asian Semi-longhair', 19, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Meggi', 425, 'Cat', 'Japanese Bobtail', 4, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Carin', 450, 'Cat', 'Sam Sawet', 14, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Rory', 595, 'Cat', 'Karelian Bobtail', 11, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Luci', 436, 'Cat', 'Serengeti', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Miguela', 758, 'Cat', 'Ojos Azules', 19, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Annetta', 906, 'Cat', 'Bambino', 12, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Mikaela', 749, 'Cat', 'British Shorthair', 14, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Stella', 11, 'Cat', 'Russian Blue', 6, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Tallia', 491, 'Cat', 'Savannah', 17, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Ernaline', 802, 'Cat', 'Sphynx', 18, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Monica', 640, 'Cat', 'Devon Rex', 5, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Robinet', 569, 'Cat', 'Colorpoint Shorthair', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Gloriana', 677, 'Cat', 'Dwarf cat', 19, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Eachelle', 984, 'Cat', 'Ukrainian Levkoy', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Andriette', 705, 'Cat', 'American Shorthair', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Queenie', 1029, 'Cat', 'Javanese', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Cornie', 571, 'Cat', 'Mekong Bobtail', 4, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Tamarra', 1309, 'Cat', 'Oriental Longhair', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Barbaraanne', 538, 'Cat', 'Korean Bobtail', 4, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Madge', 1036, 'Cat', 'American Wirehair', 11, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Nanine', 826, 'Cat', 'Ukrainian Levkoy', 4, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Sunny', 454, 'Cat', 'Snowshoe', 6, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Chere', 902, 'Cat', 'Norwegian Forest cat', 1, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Phillie', 1066, 'Cat', 'Khao Manee', 15, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Barbi', 984, 'Cat', 'Lykoi', 19, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Wallie', 822, 'Cat', 'Exotic Shorthair', 15, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Nertie', 451, 'Cat', 'European Shorthair', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Harmonia', 26, 'Cat', 'European Shorthair', 5, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Esme', 439, 'Cat', 'Sokoke', 3, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Sileas', 543, 'Cat', 'Sokoke', 15, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Fidelia', 936, 'Cat', 'Mekong Bobtail', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Lissa', 521, 'Cat', 'Kurilian Bobtail', 3, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Daphene', 841, 'Cat', 'Oregon Rex', 17, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Alyson', 919, 'Cat', 'Siberian', 15, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Ciel', 790, 'Cat', 'Snowshoe', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Corrina', 819, 'Cat', 'Colorpoint Shorthair', 12, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Ardys', 1111, 'Cat', 'Tonkinese', 17, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Arielle', 681, 'Cat', 'Donskoy', 8, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Janifer', 1222, 'Cat', 'Birman', 8, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Carlynn', 514, 'Cat', 'Napoleon', 18, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Bethanne', 1213, 'Cat', 'Australian Mist', 7, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Nola', 948, 'Cat', 'Chausie', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Petronille', 1213, 'Cat', 'Exotic Shorthair', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Lena', 648, 'Cat', 'Munchkin', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Keely', 877, 'Cat', 'Bombay', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Denny', 777, 'Cat', 'Peterbald', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Caralie', 953, 'Cat', 'European Shorthair', 2, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Izabel', 444, 'Cat', 'Ragamuffin', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Jordan', 1114, 'Cat', 'Aegean', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Talya', 9, 'Cat', 'Dwarf cat', 4, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Harriot', 1301, 'Cat', 'American Bobtail', 4, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Ofella', 841, 'Cat', 'Japanese Bobtail', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Alexi', 1023, 'Cat', 'Brazilian Shorthair', 3, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Krissie', 1207, 'Cat', 'Korean Bobtail', 11, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Matti', 515, 'Cat', 'Toyger', 1, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Diahann', 603, 'Cat', 'Brazilian Shorthair', 11, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Bethany', 801, 'Cat', 'Oriental Shorthair', 6, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Manon', 1078, 'Cat', 'Abyssinian', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Shelia', 710, 'Cat', 'Burmese', 5, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Correna', 872, 'Cat', 'Peterbald', 15, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Lizzie', 507, 'Cat', 'Ocicat', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Fedora', 553, 'Cat', 'Bombay', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Joanne', 802, 'Cat', 'Serengeti', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Alia', 808, 'Cat', 'Birman', 12, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Guenevere', 871, 'Cat', 'Serrade petit', 1, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Aile', 451, 'Cat', 'Karelian Bobtail', 11, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Blake', 492, 'Cat', 'Cheetoh', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Mabelle', 1111, 'Cat', 'European Shorthair', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Justina', 685, 'Cat', 'Ragdoll', 3, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Sapphira', 593, 'Cat', 'Norwegian Forest cat', 3, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Mariana', 11, 'Cat', 'Minskin', 14, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Batsheva', 547, 'Cat', 'Thai', 8, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Issi', 751, 'Cat', 'Pixie-bob', 12, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Elene', 1174, 'Cat', 'Balinese', 16, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Dawna', 695, 'Cat', 'Birman', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Fiorenze', 522, 'Cat', 'Turkish Angora', 11, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Lianna', 990, 'Cat', 'Ragamuffin', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Darleen', 547, 'Cat', 'Maine Coon', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Adelheid', 960, 'Cat', 'Siamese', 12, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Halimeda', 1120, 'Cat', 'Foldex', 2, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Julee', 792, 'Cat', 'Donskoy', 15, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Tandy', 476, 'Cat', 'Thai Lilac', 10, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Ursuline', 912, 'Cat', 'Asian Semi-longhair', 7, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Claudette', 948, 'Cat', 'Arabian Mau', 3, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Nicoli', 1201, 'Cat', 'Russian Blue', 1, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Rowe', 936, 'Cat', 'Napoleon', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Sari', 579, 'Cat', 'Manx', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Edi', 907, 'Cat', 'Russian Blue', 7, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Ashly', 1283, 'Cat', 'Sokoke', 11, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Violetta', 576, 'Cat', 'Persian (Modern Persian)', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Maritsa', 902, 'Cat', 'Serengeti', 3, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Carlin', 467, 'Cat', 'Dwarf cat', 11, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Naomi', 688, 'Cat', 'Selkirk Rex', 7, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Dennie', 1201, 'Cat', 'Japanese Bobtail', 1, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Jasmin', 913, 'Cat', 'Colorpoint Shorthair', 20, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Margalit', 977, 'Cat', 'Aegean', 1, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Jenda', 595, 'Cat', 'Somali', 6, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Fidelia', 743, 'Cat', 'Highlander', 4, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Mellicent', 1102, 'Cat', 'Siberian', 8, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Jacquelyn', 751, 'Cat', 'California Spangled', 12, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Elfreda', 855, 'Cat', 'Korat', 9, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Vi', 1066, 'Cat', 'Himalayan', 4, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Cathie', 1023, 'Cat', 'Ragamuffin', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Faith', 782, 'Cat', 'Bombay', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Myrilla', 810, 'Cat', 'Russian Blue', 1, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Silvana', 664, 'Cat', 'Persian (Modern Persian)', 17, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Chandal', 522, 'Cat', 'American Bobtail', 17, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Brietta', 508, 'Cat', 'Donskoy', 8, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Letisha', 859, 'Cat', 'Khao Manee', 19, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Melodee', 745, 'Cat', 'Khao Manee', 6, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Rina', 427, 'Cat', 'Dragon Li', 10, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Kessiah', 854, 'Cat', 'Tonkinese', 17, 'F');
