insert into pets (name, id, typename, breedname, age, gender) values ('Freemon', '944', 'Dog', 'Indian Spitz', 15, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Colin', '1211', 'Dog', 'Ratonero Murciano de Huerta', 17, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Don', '893', 'Dog', 'Griffon Nivernais', 15, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Erl', '1105', 'Dog', 'Koolie', 6, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Hadley', '815', 'Dog', 'Broholmer', 11, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Eadmund', '1274', 'Dog', 'Treeing Tennessee Brindle', 13, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Antons', '638', 'Dog', 'Bull Terrier', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Manny', '480', 'Dog', 'Collie, Rough', 15, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Albrecht', '590', 'Dog', 'Soft-Coated Wheaten Terrier', 11, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Clarence', '1020', 'Dog', 'Australian Terrier', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Jamaal', '874', 'Dog', 'Sinhala Hound', 10, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Simone', '898', 'Dog', 'Black and Tan Virginia Foxhound', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Lammond', '1193', 'Dog', 'Schapendoes', 10, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Alphonso', '1008', 'Dog', 'Deutsche Bracke', 11, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Yves', '968', 'Dog', 'Welsh Springer Spaniel', 8, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Carleton', '682', 'Dog', 'German Pinscher', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Spenser', '552', 'Dog', 'Toy Bulldog', 6, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Aldus', '823', 'Dog', 'Jämthund', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Duff', '940', 'Dog', 'Tyrolean Hound', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Andrey', '1328', 'Dog', 'Hanover Hound', 1, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Nicky', '829', 'Dog', 'Carpathian Shepherd', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Eben', '1047', 'Dog', 'Miniature Shar Pei', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Irvin', '1095', 'Dog', 'Armenian Gampr', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Hanan', '768', 'Dog', 'Pointer', 7, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Dwight', '1182', 'Dog', 'American Pit Bull Terrier', 1, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Davey', '638', 'Dog', 'Irish Terrier', 6, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Gordon', '1020', 'Dog', 'Tornjak', 9, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Patton', '1227', 'Dog', 'Norfolk Terrier', 9, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Allyn', '1095', 'Dog', 'Polish Greyhound', 15, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Jody', '940', 'Dog', 'Grand Anglo-Français Tricolore', 15, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Karlens', '1064', 'Dog', 'Afghan Shepherd', 3, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Dave', '1031', 'Dog', 'Gascon Saintongeois', 8, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Pattie', '1052', 'Dog', 'Kunming Wolfdog', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Alfonse', '1306', 'Dog', 'Shar Pei', 6, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Cash', '1110', 'Dog', 'Chesapeake Bay Retriever', 1, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Cullie', '811', 'Dog', 'Kai Ken', 20, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Quinn', '1229', 'Dog', 'Shiba Inu', 19, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Jermayne', '1151', 'Dog', 'Bouvier des Ardennes', 8, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Schuyler', '1218', 'Dog', 'Segugio Italiano', 4, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Patrick', '968', 'Dog', 'Saluki', 11, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Gaspar', '772', 'Dog', 'Bull Terrier (Miniature)', 9, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Art', '678', 'Dog', 'Bullenbeisser', 18, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Wilburt', '800', 'Dog', 'Armant', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Herbert', '1123', 'Dog', 'Peruvian Hairless', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Rip', '1246', 'Dog', 'Sabueso Espanol', 1, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Bo', '662', 'Dog', 'Boykin Spaniel', 6, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Kevan', '1069', 'Dog', 'Skye Terrier', 5, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Orland', '997', 'Dog', 'Tibetan Terrier', 9, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Kellen', '920', 'Dog', 'Scotch Collie', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Archaimbaud', '488', 'Dog', 'Dunker', 15, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Edward', '874', 'Dog', 'Icelandic Sheepdog', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Henri', '1243', 'Dog', 'Kerry Blue Terrier', 3, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Dagny', '1196', 'Dog', 'Otterhound', 4, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Ellwood', '785', 'Dog', 'German Shepherd', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Liam', '1170', 'Dog', 'Tenterfield Terrier', 9, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Sutherlan', '823', 'Dog', 'Alaskan Malamute', 7, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Jareb', '1044', 'Dog', 'Volpino Italiano', 3, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Hugues', '712', 'Dog', 'Greater Swiss Mountain', 4, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Rick', '525', 'Dog', 'Bosnian Coarse-haired Hound', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Jon', '1227', 'Dog', 'Central Asian Shepherd', 11, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Rabbi', '981', 'Dog', 'Hawaiian Poi', 4, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Lucien', '875', 'Dog', 'Catalan Sheepdog', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Dermot', '981', 'Dog', 'Irish Terrier', 18, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Gunther', '1229', 'Dog', 'Shikoku', 8, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Fairlie', '558', 'Dog', 'Doberman Pinscher', 14, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Rodolfo', '748', 'Dog', 'Olde English Bulldogge', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Woody', '578', 'Dog', 'American English Coonhound', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Nicholas', '1196', 'Dog', 'Collie, Rough', 14, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Culver', '720', 'Dog', 'Carpathian Shepherd', 7, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Brew', '528', 'Dog', 'Uruguayan Cimarron', 2, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Alphard', '1061', 'Dog', 'Majorca Ratter', 20, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Tailor', '564', 'Dog', 'Black Russian Terrier', 16, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Maxy', '893', 'Dog', 'Kooikerhondje', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Trace', '1160', 'Dog', 'Entlebucher Mountain', 1, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Tanney', '928', 'Dog', 'Tibetan Spaniel', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Nick', '1046', 'Dog', 'Scottish Deerhound', 6, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Garrett', '894', 'Dog', 'Tornjak', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Johnathon', '556', 'Dog', 'German Spaniel', 14, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Michale', '1034', 'Dog', 'Akita', 14, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Kareem', '594', 'Dog', 'Austrian Pinscher', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Brien', '714', 'Dog', 'Estrela Mountain', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Morgan', '1026', 'Dog', 'Tibetan Terrier', 11, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Myron', '1034', 'Dog', 'Sapsali', 8, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Jasun', '1227', 'Dog', 'Kanni', 7, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Tommy', '900', 'Dog', 'Chow Chow', 5, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Caddric', '916', 'Dog', 'Spanish Water', 5, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Jedidiah', '619', 'Dog', 'Podenco Canario', 11, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Abbie', '715', 'Dog', 'Telomian', 5, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Devland', '784', 'Dog', 'Polish Tatra Sheepdog', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Bryant', '770', 'Dog', 'Toy Fox Terrier', 8, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Bax', '1223', 'Dog', 'Icelandic Sheepdog', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Alexandros', '833', 'Dog', 'Cavalier King Charles Spaniel', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Trever', '1173', 'Dog', 'Chippiparai', 15, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Muhammad', '651', 'Dog', 'Puli', 5, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Tarrance', '1110', 'Dog', 'Black Russian Terrier', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Renaud', '887', 'Dog', 'Bleu de Gascogne, Petit', 8, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Erwin', '496', 'Dog', 'Mudi', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Waiter', '565', 'Dog', 'Schillerstövare', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Allyn', '692', 'Dog', 'Russo-European Laika', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Jackie', '1058', 'Dog', 'Bolognese', 8, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Danya', '894', 'Dog', 'Anatolian Shepherd', 12, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Elijah', '560', 'Dog', 'Basset Griffon Vendéen, Grand', 16, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Elmer', '1246', 'Dog', 'Finnish Spitz', 17, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Alasdair', '762', 'Dog', 'Japanese Spitz', 5, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Sauncho', '920', 'Dog', 'Anatolian Shepherd', 20, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Kaine', '923', 'Dog', 'Cão da Serra de Aires', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Mozes', '1098', 'Dog', 'Vizsla', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Ashley', '1298', 'Dog', 'Brittany', 2, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Abbie', '1155', 'Dog', 'Blue Heeler', 13, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Tris', '715', 'Dog', 'Czechoslovakian Wolfdog', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Pincus', '540', 'Dog', 'Russell Terrier', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Ewen', '525', 'Dog', 'Karelian Bear', 1, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Wyn', '761', 'Dog', 'West Highland White Terrier', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Lind', '706', 'Dog', 'Pug', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Malchy', '1116', 'Dog', 'Bracco Italiano', 4, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Patrick', '534', 'Dog', 'Georgian Shepherd', 7, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Bartholomeo', '987', 'Dog', 'English White Terrier', 12, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Templeton', '662', 'Dog', 'Kunming Wolfdog', 11, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Cyrillus', '590', 'Dog', 'Posavac Hound', 11, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Gherardo', '856', 'Dog', 'Bolognese', 4, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Ennis', '497', 'Dog', 'Deutsche Bracke', 8, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Hadlee', '1125', 'Dog', 'Chien-gris', 15, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Elmore', '1041', 'Dog', 'Hovawart', 17, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Warden', '1249', 'Dog', 'American Hairless Terrier', 12, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Aksel', '761', 'Dog', 'Toy Fox Terrier', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Lefty', '1037', 'Dog', 'Cantabrian Water', 8, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Irwin', '502', 'Dog', 'Bull and Terrier', 11, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Maje', '1129', 'Dog', 'Istrian Shorthaired Hound', 12, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Tabbie', '1196', 'Dog', 'English Setter', 15, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Jeth', '662', 'Dog', 'Boston Terrier', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Bryanty', '667', 'Dog', 'Mioritic', 8, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Man', '1182', 'Dog', 'Catalan Sheepdog', 7, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Berke', '1069', 'Dog', 'Chinese Crested', 11, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Calvin', '1103', 'Dog', 'American Pit Bull Terrier', 16, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Erv', '1124', 'Dog', 'Portuguese Water', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Barde', '692', 'Dog', 'Cursinu', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Farly', '1246', 'Dog', 'Norwegian Elkhound', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Shell', '940', 'Dog', 'Vizsla', 12, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Rutledge', '472', 'Dog', 'Styrian Coarse-haired Hound', 7, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Gar', '1137', 'Dog', 'Polish Greyhound', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Yorgos', '785', 'Dog', 'Old English Terrier', 18, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Saxon', '652', 'Dog', 'Black and Tan Virginia Foxhound', 6, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Ferdie', '1256', 'Dog', 'Bavarian Mountain Hound', 15, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Waldon', '1064', 'Dog', 'Boxer', 17, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Demetre', '552', 'Dog', 'Ratonero Valenciano', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Rudolfo', '979', 'Dog', 'Volpino Italiano', 12, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Drake', '1105', 'Dog', 'Briquet Griffon Vendéen', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Giulio', '1020', 'Dog', 'Old Danish Pointer', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Gram', '805', 'Dog', 'Cão de Gado Transmontano', 10, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Jakie', '560', 'Dog', 'Šarplaninac', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Seymour', '875', 'Dog', 'Polish Hunting', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Trip', '1173', 'Dog', 'Thai Ridgeback', 20, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Kean', '556', 'Dog', 'French Brittany', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Wyatan', '944', 'Dog', 'Doberman Pinscher', 6, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Maximilianus', '610', 'Dog', 'Black and Tan Virginia Foxhound', 10, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Brook', '1218', 'Dog', 'Alaunt', 7, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Otis', '686', 'Dog', 'Dunker', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Alfredo', '894', 'Dog', 'Mackenzie River Husky', 8, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Artus', '1080', 'Dog', 'Paisley Terrier', 2, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Cazzie', '652', 'Dog', 'Olde English Bulldogge', 12, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Johan', '968', 'Dog', 'Eurohound', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Alwin', '1182', 'Dog', 'Seskar Seal', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Basilius', '914', 'Dog', 'Peruvian Hairless', 2, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Ogdon', '602', 'Dog', 'Golden Retriever', 11, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Simmonds', '1061', 'Dog', 'Pomeranian', 17, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Rowland', '1105', 'Dog', 'Griffon Bleu de Gascogne', 15, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Clem', '1328', 'Dog', 'Tosa', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Cully', '1170', 'Dog', 'Porcelaine', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Fonzie', '486', 'Dog', 'Hokkaido', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Derril', '997', 'Dog', 'Curly-Coated Retriever', 11, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Hazel', '1061', 'Dog', 'Scottish Deerhound', 4, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Bourke', '619', 'Dog', 'Miniature Shar Pei', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Neill', '1173', 'Dog', 'Pyrenean Mastiff', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Morty', '517', 'Dog', 'Toy Fox Terrier', 17, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Doyle', '651', 'Dog', 'Bohemian Shepherd', 2, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Brand', '1256', 'Dog', 'Cretan Hound', 9, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Jens', '755', 'Dog', 'Thai Bangkaew', 14, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Friedrich', '630', 'Dog', 'Cantabrian Water', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Sherwood', '1229', 'Dog', 'Basset Artésien Normand', 15, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Jud', '944', 'Dog', 'Ratonero Valenciano', 16, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Wallis', '596', 'Dog', 'Carpathian Shepherd', 3, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Killie', '770', 'Dog', 'Finnish Spitz', 9, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Darrin', '968', 'Dog', 'Irish Water Spaniel', 14, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Steffen', '1323', 'Dog', 'Shikoku', 12, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Jameson', '1076', 'Dog', 'German Spitz', 6, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Claudianus', '1075', 'Dog', 'Hygenhund', 4, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Theodoric', '1290', 'Dog', 'Serbian Hound', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Cly', '714', 'Dog', 'Dunker', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Farrel', '1292', 'Dog', 'Smålandsstövare', 10, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Briano', '614', 'Dog', 'Saluki', 6, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Gare', '638', 'Dog', 'Basset Griffon Vendéen, Petit', 9, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Denney', '898', 'Dog', 'Vanjari Hound', 6, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Hart', '1135', 'Dog', 'Tornjak', 18, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Gregor', '1075', 'Dog', 'Paisley Terrier', 17, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Ely', '1025', 'Dog', 'Huntaway', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Aloin', '827', 'Dog', 'Alano Espanol', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Dalton', '1058', 'Dog', 'Vanjari Hound', 12, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Gordie', '1256', 'Dog', 'Irish Wolfhound', 11, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Emmet', '900', 'Dog', 'Bleu de Gascogne, Grand', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Gabie', '707', 'Dog', 'Moscow Water', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Gabby', '1170', 'Dog', 'Miniature Pinscher', 18, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Harcourt', '778', 'Dog', 'Border Terrier', 2, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Inness', '472', 'Dog', 'Austrian Pinscher', 2, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Ludovico', '512', 'Dog', 'Tibetan Spaniel', 2, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Hubie', '667', 'Dog', 'Mudhol Hound', 18, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Fredric', '525', 'Dog', 'Basset Fauve de Bretagne', 7, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Urban', '722', 'Dog', 'Sabueso Espanol', 11, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Ephraim', '1119', 'Dog', 'Otterhound', 4, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Jefferey', '1040', 'Dog', 'English Mastiff', 18, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Beale', '1211', 'Dog', 'Alopekis', 7, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Burr', '581', 'Dog', 'Pug', 6, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Jabez', '1146', 'Dog', 'Dogue de Bordeaux', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Ryley', '1037', 'Dog', 'Sealyham Terrier', 16, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Mohandis', '493', 'Dog', 'Great Dane', 2, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Gary', '1124', 'Dog', 'Irish Water Spaniel', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Klement', '922', 'Dog', 'Hovawart', 2, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Waring', '922', 'Dog', 'Lakeland Terrier', 13, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Eamon', '610', 'Dog', 'Mucuchies', 2, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Gil', '1129', 'Dog', 'Griffon Bruxellois', 12, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Llewellyn', '630', 'Dog', 'Chinese Chongqing', 6, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Gal', '1211', 'Dog', 'Border Collie', 15, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Aluin', '564', 'Dog', 'Burgos Pointer', 15, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Gibby', '1255', 'Dog', 'Beagle', 3, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Tan', '651', 'Dog', 'Collie, Smooth', 4, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Neville', '610', 'Dog', 'Polish Hunting', 6, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Penny', '477', 'Dog', 'Beagle-Harrier', 15, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Seward', '1034', 'Dog', 'Bouvier des Flandres', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Eugene', '1308', 'Dog', 'Appenzeller Sennenhund', 6, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Thorn', '1306', 'Dog', 'Karelian Bear', 7, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Prent', '678', 'Dog', 'Taiwan', 2, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Olenolin', '573', 'Dog', 'Lithuanian Hound', 10, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Anson', '1124', 'Dog', 'Spinone Italiano', 15, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Abramo', '686', 'Dog', 'Braque du Bourbonnais', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Dario', '525', 'Dog', 'Azawakh', 13, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Alfie', '768', 'Dog', 'Poodle', 4, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Sammy', '1290', 'Dog', 'Dutch Smoushond', 11, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Wendall', '549', 'Dog', 'Kerry Blue Terrier', 5, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Murvyn', '1243', 'Dog', 'Grand Anglo-Français Blanc et Noir', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Jens', '791', 'Dog', 'Thai Ridgeback', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Lauritz', '473', 'Dog', 'Chien Français Tricolore', 15, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Pietro', '532', 'Dog', 'Braque du Bourbonnais', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Aguste', '887', 'Dog', 'Swedish Vallhund', 11, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Nefen', '1080', 'Dog', 'Danish-Swedish Farmdog', 20, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Rupert', '875', 'Dog', 'Miniature American Shepherd', 3, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Lin', '785', 'Dog', 'Old Time Farm Shepherd', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Hansiain', '635', 'Dog', 'Norwegian Buhund', 12, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Torre', '512', 'Dog', 'Boerboel', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Giulio', '914', 'Dog', 'Braque d''Auvergne', 15, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Jess', '920', 'Dog', 'Slovenský Kopov', 7, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Brent', '1176', 'Dog', 'Kishu Ken', 4, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Aubert', '505', 'Dog', 'Central Asian Shepherd', 12, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Brett', '762', 'Dog', 'Great Pyrenees', 17, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Fraze', '1080', 'Dog', 'Lithuanian Hound', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Worden', '1306', 'Dog', 'Welsh Corgi, Cardigan', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Alain', '986', 'Dog', 'Australian Terrier', 1, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Martin', '815', 'Dog', 'Cavalier King Charles Spaniel', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Eugene', '1135', 'Dog', 'Thai Ridgeback', 3, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Niven', '755', 'Dog', 'Garafian Shepherd', 20, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Lamont', '1064', 'Dog', 'Finnish Lapphund', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Barnaby', '1047', 'Dog', 'Catalan Sheepdog', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Russ', '667', 'Dog', 'Scottish Deerhound', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Fidelio', '550', 'Dog', 'Treeing Cur', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Curcio', '914', 'Dog', 'Braque Saint-Germain', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Wallas', '1085', 'Dog', 'Maremma Sheepdog', 9, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Vassili', '1232', 'Dog', 'Guatemalan Dogo', 13, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Davide', '1172', 'Dog', 'Treeing Walker Coonhound', 1, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Godfry', '857', 'Dog', 'Bosnian Coarse-haired Hound', 6, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Hermie', '573', 'Dog', 'Great Pyrenees', 6, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Nickey', '908', 'Dog', 'Alpine Mastiff', 16, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Brendan', '1244', 'Dog', 'Poodle', 4, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Bayard', '1151', 'Dog', 'Puli', 15, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('York', '969', 'Dog', 'Manchester Terrier', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Dorie', '1223', 'Dog', 'Old English Sheepdog', 8, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Enrique', '1037', 'Dog', 'Bull and Terrier', 1, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Robb', '1308', 'Dog', 'Tamaskan', 10, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Patsy', '578', 'Dog', 'Poodle', 10, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Trent', '660', 'Dog', 'Scottish Terrier', 10, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Irvine', '1326', 'Dog', 'Australian Cattle', 6, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Abeu', '588', 'Dog', 'Shetland Sheepdog', 16, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Artie', '770', 'Dog', 'Grand Anglo-Français Tricolore', 12, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Ruggiero', '815', 'Dog', 'Greenland', 12, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Myca', '619', 'Dog', 'Billy', 2, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Paxon', '1230', 'Dog', 'Small Greek Domestic', 15, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Baldwin', '1326', 'Dog', 'Hovawart', 4, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Fabiano', '857', 'Dog', 'Tamaskan', 4, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Rick', '1123', 'Dog', 'French Spaniel', 18, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Martainn', '1075', 'Dog', 'Black and Tan Virginia Foxhound', 4, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Tremayne', '1016', 'Dog', 'Shiba Inu', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Westley', '564', 'Dog', 'Jämthund', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Pate', '979', 'Dog', 'Caucasian Shepherd', 6, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Monti', '1137', 'Dog', 'Akita', 11, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Ruddie', '501', 'Dog', 'Chinese Crested', 2, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Billie', '715', 'Dog', 'Northern Inuit', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Greggory', '670', 'Dog', 'Alopekis', 2, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Mervin', '564', 'Dog', 'Akbash', 20, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Neddie', '572', 'Dog', 'Caucasian Shepherd', 7, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Tremaine', '778', 'Dog', 'Brazilian Dogo', 16, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Sidnee', '1176', 'Dog', 'Molossus of Epirus', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Kermit', '707', 'Dog', 'Blue Heeler', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Norris', '1103', 'Dog', 'Miniature Shar Pei', 16, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Jae', '686', 'Dog', 'Catahoula Leopard', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Rickie', '525', 'Dog', 'Chien Français Tricolore', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Valdemar', '654', 'Dog', 'St. John''s water', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Thayne', '1294', 'Dog', 'Schweizerischer Niederlaufhund', 4, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Kristo', '654', 'Dog', 'Border Terrier', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Dudley', '549', 'Dog', 'Canadian Eskimo', 8, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Culver', '910', 'Dog', 'German Shorthaired Pointer', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Franklyn', '1275', 'Dog', 'McNab', 5, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Vincent', '635', 'Dog', 'Guatemalan Dogo', 16, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Shell', '1151', 'Dog', 'Afghan Hound', 13, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Desi', '1328', 'Dog', 'Carolina', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Bat', '692', 'Dog', 'Cirneco dell''Etna', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Ike', '961', 'Dog', 'West Highland White Terrier', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Freedman', '968', 'Dog', 'Golden Retriever', 8, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Nil', '549', 'Dog', 'Pyrenean Mastiff', 1, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Jedediah', '880', 'Dog', 'Chinook', 1, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Kurtis', '987', 'Dog', 'Armenian Gampr', 1, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Elwyn', '493', 'Dog', 'Hare Indian', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Quincy', '748', 'Dog', 'Alaskan Klee Kai', 2, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Lionello', '1256', 'Dog', 'Dunker', 3, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Tammy', '472', 'Dog', 'Molossus', 2, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Man', '550', 'Dog', 'Ariege Pointer', 5, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Brion', '1031', 'Dog', 'Hanover Hound', 4, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Waylin', '1314', 'Dog', 'Taigan', 4, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Ancell', '573', 'Dog', 'Braque Saint-Germain', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Umberto', '1116', 'Dog', 'Fila Brasileiro', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Duane', '1215', 'Dog', 'Wirehaired Vizsla', 1, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Brantley', '497', 'Dog', 'Dunker', 10, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Bentlee', '969', 'Dog', 'Elo', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Giraldo', '1193', 'Dog', 'Small Greek Domestic', 15, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Melvin', '1245', 'Dog', 'Guatemalan Dogo', 15, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Elden', '552', 'Dog', 'Tyrolean Hound', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Kingston', '747', 'Dog', 'Saint-Usuge Spaniel', 11, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Owen', '1008', 'Dog', 'German Shepherd', 4, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Erastus', '470', 'Dog', 'Bouvier des Ardennes', 6, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Keven', '894', 'Dog', 'Pekingese', 17, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Brody', '723', 'Dog', 'Ariegeois', 10, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Huberto', '654', 'Dog', 'Skye Terrier', 12, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Dugald', '662', 'Dog', 'Vanjari Hound', 11, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Conrado', '590', 'Dog', 'Thai Ridgeback', 10, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Ellary', '797', 'Dog', 'Hygenhund', 16, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Link', '564', 'Dog', 'Bullmastiff', 9, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Amos', '1047', 'Dog', 'Berger Picard', 1, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Nahum', '784', 'Dog', 'Sabueso Espanol', 13, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Stefano', '1064', 'Dog', 'Taigan', 16, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Nehemiah', '659', 'Dog', 'Hygenhund', 6, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('West', '525', 'Dog', 'Bloodhound', 5, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Archy', '660', 'Dog', 'Swedish Lapphund', 4, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Dannel', '968', 'Dog', 'Cantabrian Water', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Harland', '1212', 'Dog', 'Toy Fox Terrier', 9, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Jarred', '1196', 'Dog', 'Black and Tan Coonhound', 12, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Lon', '1155', 'Dog', 'Black Mouth Cur', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Georas', '572', 'Dog', 'Plummer Terrier', 17, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Moishe', '1026', 'Dog', 'Brazilian Terrier', 8, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Emmott', '928', 'Dog', 'Terceira Mastiff', 19, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Hayyim', '1116', 'Dog', 'Akita', 20, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Bearnard', '747', 'Dog', 'Slovenský Kopov', 14, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Keelby', '613', 'Dog', 'Tornjak', 11, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Pavel', '1137', 'Dog', 'Chippiparai', 18, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Fleming', '1123', 'Dog', 'Hygenhund', 5, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Hastings', '805', 'Dog', 'West Siberian Laika', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Ricky', '1275', 'Dog', 'Newfoundland', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Virge', '1100', 'Dog', 'Peruvian Hairless', 7, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Addie', '1294', 'Dog', 'English Water Spaniel', 16, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Roma', '1290', 'Dog', 'Phu Quoc Ridgeback', 7, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Philbert', '1274', 'Dog', 'English Shepherd', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Josh', '1028', 'Dog', 'Beagle', 5, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Alden', '654', 'Dog', 'Treeing Tennessee Brindle', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Rudolph', '654', 'Dog', 'Moscow Water', 10, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Kasper', '1176', 'Dog', 'West Highland White Terrier', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Torrance', '1328', 'Dog', 'St. Bernard', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Elmo', '1275', 'Dog', 'Scottish Deerhound', 7, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Jacobo', '542', 'Dog', 'Alaskan husky', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Conrad', '1005', 'Dog', 'Wirehaired Pointing Griffon', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Dorey', '1098', 'Dog', 'American English Coonhound', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Raleigh', '1080', 'Dog', 'Grand Anglo-Français Blanc et Orange', 6, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Osbert', '1080', 'Dog', 'Bloodhound', 18, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Nigel', '823', 'Dog', 'Peruvian Hairless', 16, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Kasper', '638', 'Dog', 'American Water Spaniel', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Pren', '1026', 'Dog', 'Spanish Mastiff', 3, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Gibbie', '851', 'Dog', 'Australian Terrier', 1, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Phil', '659', 'Dog', 'Havanese', 16, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Clay', '1086', 'Dog', 'Lakeland Terrier', 6, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Arnuad', '635', 'Dog', 'Greater Swiss Mountain', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Brucie', '987', 'Dog', 'Ratonero Murciano de Huerta', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Quinton', '565', 'Dog', 'Beagle-Harrier', 15, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Marc', '1173', 'Dog', 'Chien Français Blanc et Orange', 11, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Siward', '1149', 'Dog', 'Paisley Terrier', 7, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Lon', '644', 'Dog', 'Pekingese', 1, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Wain', '1170', 'Dog', 'Belgian Shepherd Dog (Tervuren)', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Carling', '682', 'Dog', 'Istrian Shorthaired Hound', 1, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Ambrose', '1085', 'Dog', 'Pandikona Hunting', 19, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Francesco', '1173', 'Dog', 'Small Greek Domestic', 11, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Marcello', '770', 'Dog', 'Cão de Castro Laboreiro', 13, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Ashton', '1218', 'Dog', 'Taiwan', 8, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Blake', '817', 'Dog', 'New Zealand Heading', 15, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Vasili', '698', 'Dog', 'Rastreador Brasileiro', 6, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Farlee', '1227', 'Dog', 'Norrbottenspets', 4, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Sandy', '904', 'Dog', 'Pekingese', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Asa', '678', 'Dog', 'Blue Heeler', 12, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Westbrook', '651', 'Dog', 'Italian Greyhound', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Alfy', '1095', 'Dog', 'Manchester Terrier', 9, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Caldwell', '722', 'Dog', 'Greek Harehound', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Birk', '473', 'Dog', 'Seskar Seal', 1, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Sherlock', '747', 'Dog', 'Rampur Greyhound', 5, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Rod', '1002', 'Dog', 'Pont-Audemer Spaniel', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Kellen', '1206', 'Dog', 'Mudi', 1, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Earle', '1119', 'Dog', 'Black and Tan Virginia Foxhound', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Dallas', '800', 'Dog', 'Croatian Sheepdog', 18, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Tremain', '1232', 'Dog', 'Dunker', 7, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Josiah', '881', 'Dog', 'Spinone Italiano', 17, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Gordy', '550', 'Dog', 'Alpine Spaniel', 15, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Tammie', '1086', 'Dog', 'Bully Kutta', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Cirillo', '1269', 'Dog', 'Bully Kutta', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Ermin', '1041', 'Dog', 'Tamaskan', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Fabiano', '707', 'Dog', 'Basset Hound', 16, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Glen', '1293', 'Dog', 'Mudi', 1, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Brewster', '968', 'Dog', 'Berger Blanc Suisse', 20, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Garrard', '900', 'Dog', 'Cavalier King Charles Spaniel', 2, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Haywood', '1146', 'Dog', 'American Cocker Spaniel', 6, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Leopold', '834', 'Dog', 'Norfolk Terrier', 8, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Schuyler', '1046', 'Dog', 'Kunming Wolfdog', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Thadeus', '642', 'Dog', 'Alaunt', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Roldan', '923', 'Dog', 'Bullmastiff', 13, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Kenny', '1332', 'Dog', 'Afghan Shepherd', 9, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Lewes', '574', 'Dog', 'Basset Bleu de Gascogne', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Bill', '525', 'Dog', 'Combai', 20, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Cord', '833', 'Dog', 'Portuguese Pointer', 4, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Auberon', '1080', 'Dog', 'Lapponian Herder', 11, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Klemens', '834', 'Dog', 'Bluetick Coonhound', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Shaun', '614', 'Dog', 'Jagdterrier', 8, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Abdel', '472', 'Dog', 'Kangal', 15, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Obediah', '1025', 'Dog', 'West Highland White Terrier', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Alexandre', '651', 'Dog', 'Griffon Bruxellois', 10, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Roddie', '928', 'Dog', 'Small Greek Domestic', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Byran', '1328', 'Dog', 'Cretan Hound', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Boyd', '477', 'Dog', 'Talbot', 14, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Lovell', '496', 'Dog', 'Grand Anglo-Français Tricolore', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Herbie', '636', 'Dog', 'Azawakh', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Jordon', '480', 'Dog', 'Hovawart', 2, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Dominick', '1332', 'Dog', 'Kooikerhondje', 8, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Nicholas', '712', 'Dog', 'Norfolk Terrier', 10, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Nikolai', '1061', 'Dog', 'Cavalier King Charles Spaniel', 3, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Fraze', '652', 'Dog', 'Molossus of Epirus', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Wilburt', '880', 'Dog', 'Fila Brasileiro', 8, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Avictor', '698', 'Dog', 'Seppala Siberian Sleddog', 20, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Jeremie', '594', 'Dog', 'Czechoslovakian Wolfdog', 12, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Tabor', '928', 'Dog', 'Tenterfield Terrier', 2, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Aluin', '1243', 'Dog', 'Tweed Water Spaniel', 20, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Izzy', '662', 'Dog', 'Basenji', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Hobey', '611', 'Dog', 'Mountain Cur', 19, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Fitzgerald', '923', 'Dog', 'Wirehaired Vizsla', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Ambrosius', '1069', 'Dog', 'Estonian Hound', 10, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Skyler', '558', 'Dog', 'Poitevin', 7, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Werner', '574', 'Dog', 'Siberian Husky', 8, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Klement', '1028', 'Dog', 'Kerry Beagle', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Chevy', '1314', 'Dog', 'Danish-Swedish Farmdog', 2, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Jedd', '1275', 'Dog', 'Mountain Cur', 7, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Correy', '542', 'Dog', 'Wetterhoun', 17, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Magnum', '1075', 'Dog', 'German Roughhaired Pointer', 5, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Alford', '791', 'Dog', 'Plummer Terrier', 4, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Yves', '1040', 'Dog', 'Braque du Puy', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Whitaker', '470', 'Dog', 'Basset Artésien Normand', 12, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Rorke', '1031', 'Dog', 'Chinese Chongqing', 2, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Tanney', '706', 'Dog', 'Pandikona Hunting', 6, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Nicholas', '1227', 'Dog', 'Chinese Imperial', 18, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Gardiner', '1047', 'Dog', 'Dunker', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Berne', '1269', 'Dog', 'Hanover Hound', 13, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Enoch', '670', 'Dog', 'Schillerstövare', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Mac', '803', 'Dog', 'Austrian Pinscher', 11, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Rutger', '1044', 'Dog', 'Kuvasz', 7, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Natty', '780', 'Dog', 'English Toy Terrier (Black & Tan)', 17, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Mendie', '1314', 'Dog', 'Grand Anglo-Français Blanc et Orange', 7, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Elnar', '1229', 'Dog', 'Toy Fox Terrier', 1, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Bendix', '1100', 'Dog', 'Vizsla', 12, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Gustav', '991', 'Dog', 'Griffon Fauve de Bretagne', 15, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Ivan', '1069', 'Dog', 'Brittany', 4, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Odie', '602', 'Dog', 'Beagle-Harrier', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Robinet', '1294', 'Dog', 'Chow Chow', 3, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Erhard', '920', 'Dog', 'Bull Terrier (Miniature)', 11, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Zackariah', '1026', 'Dog', 'Sinhala Hound', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Bentley', '630', 'Dog', 'Irish Water Spaniel', 11, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Roth', '581', 'Dog', 'Russian Tracker', 10, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Rainer', '738', 'Dog', 'Alaskan husky', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Max', '574', 'Dog', 'Leonberger', 19, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Eliot', '1293', 'Dog', 'Collie, Smooth', 9, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Jefferey', '961', 'Dog', 'Bichon Frisé', 13, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Aland', '1317', 'Dog', 'English Toy Terrier (Black & Tan)', 12, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Llywellyn', '1041', 'Dog', 'Basque Shepherd', 18, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Noland', '532', 'Dog', 'Portuguese Pointer', 20, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Sollie', '1116', 'Dog', 'Welsh Corgi, Pembroke', 7, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Wynn', '505', 'Dog', 'Galician Cattle', 14, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Urbanus', '908', 'Dog', 'Dutch Shepherd', 2, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Torrey', '1046', 'Dog', 'Sapsali', 8, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Murdock', '1025', 'Dog', 'Norfolk Spaniel', 1, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Neron', '1055', 'Dog', 'Karakachan', 20, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Waylin', '1031', 'Dog', 'Bearded Collie', 3, 'F');
insert into pets (name, id, typename, breedname, age, gender) values ('Torey', '1244', 'Dog', 'Norfolk Terrier', 19, 'M');
insert into pets (name, id, typename, breedname, age, gender) values ('Binky', '914', 'Dog', 'Grand Anglo-Français Blanc et Noir', 15, 'M');
